"""Interactive profile creator — walks the user through creating a new YAML profile."""

import logging
import re
from pathlib import Path

from sources import SOURCE_REGISTRY
from sources.yaml_source import load_all_store_definitions
from utils.validation import validate_profile

logger = logging.getLogger(__name__)

BASE_DIR = Path(__file__).parent.parent
PROFILES_DIR = BASE_DIR / "profiles"


def _ask(prompt: str, default: str = "") -> str:
    """Ask a question with an optional default value."""
    if default:
        raw = input(f"{prompt} [{default}]: ").strip()
        return raw if raw else default
    return input(f"{prompt}: ").strip()


def _ask_int(prompt: str, default: int | None = None) -> int:
    """Ask for an integer with optional default."""
    while True:
        raw = _ask(prompt, str(default) if default is not None else "")
        try:
            return int(raw)
        except ValueError:
            print("  Please enter a valid number.")


def _ask_list(prompt: str) -> list[str]:
    """Ask for a comma-separated list, return list of stripped strings."""
    raw = _ask(prompt)
    if not raw:
        return []
    return [item.strip() for item in raw.split(",") if item.strip()]


def _ask_yes_no(prompt: str, default: bool = True) -> bool:
    """Ask a yes/no question."""
    suffix = "Y/n" if default else "y/N"
    raw = input(f"{prompt} [{suffix}]: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes")


def _get_available_sources() -> list[dict]:
    """Get list of available sources with their type info."""
    store_defs = load_all_store_definitions()
    sources = []

    for name in sorted(SOURCE_REGISTRY.keys()):
        if name in store_defs:
            store = store_defs[name]
            sources.append(
                {
                    "name": name,
                    "type": store.get("type", "catalog"),
                    "kind": "yaml_store",
                }
            )
        elif name == "pepper":
            sources.append({"name": "pepper", "type": "search", "kind": "python"})
        elif name == "web":
            sources.append({"name": "web", "type": "generic", "kind": "python"})
        else:
            sources.append({"name": name, "type": "unknown", "kind": "python"})

    return sources


def _configure_source(source_info: dict) -> dict | None:
    """Ask the user to configure a single source. Returns config dict or None."""
    name = source_info["name"]
    stype = source_info["type"]

    if name == "web":
        print("  Skipping 'web' — configure it manually in the YAML (needs CSS selectors).")
        return None

    if name == "pepper":
        print("  Pepper.pl — enter search URLs (e.g. https://www.pepper.pl/search?q=your+query)")
        urls = _ask_list("  URLs (comma-separated)")
        if not urls:
            return None
        return {"urls": urls}

    if stype == "search":
        queries = _ask_list(f"  Search queries for {name} (comma-separated)")
        if not queries:
            return None
        return {"queries": queries}

    if stype == "catalog":
        urls = _ask_list(f"  URLs for {name} catalog pages (comma-separated)")
        if not urls:
            return None
        return {"urls": urls}

    return None


def _generate_yaml(profile: dict, name: str) -> str:
    """Generate a well-commented YAML profile string."""
    lines = []
    lines.append(f"# Profile: {name}")
    lines.append("# Generated by: deal-hunter --init")
    lines.append("#")
    lines.append(f"# Test it:  python deal_hunter.py --profile {name} --verify")
    lines.append(f"# Run it:   python deal_hunter.py --profile {name}")
    lines.append("#")
    lines.append("# Full reference: docs/creating-profiles.md")
    lines.append("")

    lines.append("# Profile identity — shown in alerts and logs")
    lines.append(f"name: {name}")
    lines.append(f'emoji: "{profile.get("emoji", chr(0x1F50D))}"')
    lines.append("")

    lines.append("# Where to search — each key maps to a registered source plugin")
    lines.append("sources:")
    for source_name, source_config in profile.get("sources", {}).items():
        lines.append(f"  {source_name}:")
        if "urls" in source_config:
            lines.append("    urls:")
            for url in source_config["urls"]:
                lines.append(f'      - "{url}"')
        if "queries" in source_config:
            lines.append("    queries:")
            for query in source_config["queries"]:
                lines.append(f'      - "{query}"')
    lines.append("")

    budget = profile.get("budget", {})
    lines.append("# Price range (PLN) — deals outside this range get score penalties")
    lines.append("budget:")
    lines.append(f"  min: {budget.get('min', 100)}")
    lines.append(f"  max: {budget.get('max', 500)}")
    lines.append("")

    score_rules = profile.get("score_rules", {})
    if score_rules:
        lines.append(
            "# Positive scoring rules — each keyword adds points when found in title/description"
        )
        lines.append("score_rules:")
        for keyword, points in score_rules.items():
            lines.append(f'  "{keyword}": {points}')
    else:
        lines.append("# Positive scoring rules — add keywords and point values")
        lines.append("score_rules: {}")
    lines.append("")

    lines.append("# Penalties — keywords that reduce score (use negative values)")
    penalties = profile.get("penalties", {})
    if penalties:
        lines.append("penalties:")
        for keyword, points in penalties.items():
            lines.append(f'  "{keyword}": {points}')
    else:
        lines.append("penalties: {}")
    lines.append("")

    excluded = profile.get("excluded_words", [])
    if excluded:
        lines.append("# Hard filters — any match = deal is rejected outright")
        lines.append("excluded_words:")
        for word in excluded:
            lines.append(f'  - "{word}"')
        lines.append("")

    lines.append("# Scoring thresholds — control which deals trigger alerts")
    lines.append(f"score_threshold: {profile.get('score_threshold', 40)}")
    lines.append(f"score_threshold_alert: {profile.get('score_threshold_alert', 80)}")
    lines.append("")

    lines.append("# Telegram settings")
    tg = profile.get("telegram", {})
    lines.append("telegram:")
    topic_id = tg.get("topic_id")
    lines.append(f"  topic_id: {topic_id if topic_id else 'null'}")
    lines.append(f"  max_alerts: {tg.get('max_alerts', 5)}")
    lines.append("")

    return "\n".join(lines)


def run_init() -> None:
    """Interactive profile creator. Walks through creating a new YAML profile."""
    try:
        print("\n=== Deal Hunter — Profile Creator ===\n")

        # Profile name
        while True:
            name = _ask("Profile name (lowercase, no spaces, e.g. 'headphones')")
            if not name:
                print("  Name is required.")
                continue
            if not re.match(r"^[a-z0-9_]+$", name):
                print("  Use only lowercase letters, numbers, and underscores.")
                continue
            profile_path = PROFILES_DIR / f"{name}.yaml"
            if profile_path.exists():
                print(f"  Profile '{name}' already exists at {profile_path}")
                if not _ask_yes_no("  Overwrite?", default=False):
                    continue
            break

        # Emoji
        emoji = _ask("Emoji for alerts", "\U0001f50d")

        # Sources
        available = _get_available_sources()
        print("\nAvailable sources:")
        for i, src in enumerate(available, 1):
            label = f"{src['name']} ({src['type']})"
            print(f"  {i}. {label}")

        print("\nEnter source numbers separated by commas (e.g. '1,3'):")
        chosen_raw = _ask("Sources")
        chosen_indices: list[int] = []
        for part in chosen_raw.split(","):
            part = part.strip()
            if part.isdigit():
                idx = int(part) - 1
                if 0 <= idx < len(available):
                    chosen_indices.append(idx)

        sources_config: dict = {}
        for idx in chosen_indices:
            src = available[idx]
            print(f"\n--- Configuring: {src['name']} ---")
            config = _configure_source(src)
            if config:
                sources_config[src["name"]] = config

        if not sources_config:
            print("\nNo sources configured. At least one source is required.")
            return

        # Budget
        print("\nBudget range (PLN):")
        while True:
            budget_min = _ask_int("  Minimum price", 100)
            budget_max = _ask_int("  Maximum price", 500)
            if budget_min < budget_max:
                break
            print("  Minimum must be less than maximum. Try again.")

        # Score rules
        print("\nKeywords to score positively (comma-separated):")
        print("  Each keyword will get 30 points. Edit the YAML to fine-tune.")
        keywords = _ask_list("  Keywords")
        score_rules = {kw: 30 for kw in keywords}

        # Excluded words
        print("\nExcluded words — deals containing these are rejected (comma-separated):")
        excluded = _ask_list("  Excluded words")

        # Notifications
        print("\nNotifications:")
        use_telegram = _ask_yes_no("  Enable Telegram alerts?", default=True)
        tg_config: dict = {}
        if use_telegram:
            topic_id_raw = _ask("  Telegram topic ID (0 or leave empty for no topic)", "0")
            try:
                topic_id = int(topic_id_raw)
            except ValueError:
                print("  Invalid topic ID, using no topic.")
                topic_id = None
            max_alerts = _ask_int("  Max alerts per run", 5)
            tg_config = {"topic_id": topic_id if topic_id else None, "max_alerts": max_alerts}
        else:
            tg_config = {"topic_id": None, "max_alerts": 5}

        # Build profile dict
        profile = {
            "name": name,
            "emoji": emoji,
            "sources": sources_config,
            "budget": {"min": budget_min, "max": budget_max},
            "score_rules": score_rules,
            "penalties": {},
            "score_threshold": 40,
            "score_threshold_alert": 80,
            "telegram": tg_config,
        }
        if excluded:
            profile["excluded_words"] = excluded

        # Validate
        errors = validate_profile(profile)
        if errors:
            print("\nWarning — generated profile has validation issues:")
            for err in errors:
                print(f"  - {err}")
            if not _ask_yes_no("  Save anyway?", default=False):
                print("Aborted.")
                return

        # Generate YAML
        yaml_content = _generate_yaml(profile, name)

        # Write
        PROFILES_DIR.mkdir(exist_ok=True)
        profile_path = PROFILES_DIR / f"{name}.yaml"
        with open(profile_path, "w", encoding="utf-8") as f:
            f.write(yaml_content)

        print(f"\n\u2705 Profile saved to: {profile_path}")
        print("\nNext steps:")
        print(f"  1. Review and tweak: {profile_path}")
        print(f"  2. Test it: python deal_hunter.py --profile {name} --verify")
        print(f"  3. Run it:  python deal_hunter.py --profile {name}")

    except KeyboardInterrupt:
        print("\n\nAborted.")
    except EOFError:
        print("\n\nAborted.")
